/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef ANTIVIRUS_INSTALLER_PRIVATE_H
#define ANTIVIRUS_INSTALLER_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"6.6.6.6"
#define VER_MAJOR	6
#define VER_MINOR	6
#define VER_RELEASE	6
#define VER_BUILD	6
#define COMPANY_NAME	"Hugopako"
#define FILE_VERSION	"6.6.6.6"
#define FILE_DESCRIPTION	"DROWNING YOSHI EPIC CHAPTER 666 THE (NOT) LAST"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"noskid"
#define PRODUCT_VERSION	"6.6.6.6"

#endif /*ANTIVIRUS_INSTALLER_PRIVATE_H*/
